In [2]:
import pandas as pd

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.width', None)       
pd.set_option('display.float_format', '{:.2f}'.format)

In [3]:
df =pd.read_csv("customer_shopping_behavior.csv")
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.10,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.10,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.10,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.50,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.70,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [4]:
df.shape

(3900, 18)

In [7]:
df.columns

Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Shipping Type',
       'Discount Applied', 'Promo Code Used', 'Previous Purchases',
       'Payment Method', 'Frequency of Purchases'],
      dtype='str')

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   str
 3   Item Purchased          3900 non-null   str
 4   Category                3900 non-null   str
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   str
 7   Size                    3900 non-null   str
 8   Color                   3900 non-null   str
 9   Season                  3900 non-null   str
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   str
 12  Shipping Type           3900 non-null   str
 13  Discount Applied        3900 non-null   str
 14  Promo Code Used         3900 non-null   str
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   str
 17  Frequency of Purchases  3900 non-null   str
dtypes: float64(1), int64(4), str(13)
memory usage: 548.6 KB

In [15]:
df.describe(include = "all")

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.00,3900.00,3900,3900,3900,3900.00,3900,3900,3900,3900,3863.00,3900,3900,3900,3900,3900.00,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.50,44.07,NaN,NaN,NaN,59.76,NaN,NaN,NaN,NaN,3.75,NaN,NaN,NaN,NaN,25.35,NaN,NaN
std,1125.98,15.21,NaN,NaN,NaN,23.69,NaN,NaN,NaN,NaN,0.72,NaN,NaN,NaN,NaN,14.45,NaN,NaN
min,1.00,18.00,NaN,NaN,NaN,20.00,NaN,NaN,NaN,NaN,2.50,NaN,NaN,NaN,NaN,1.00,NaN,NaN
25%,975.75,31.00,NaN,NaN,NaN,39.00,NaN,NaN,NaN,NaN,3.10,NaN,NaN,NaN,NaN,13.00,NaN,NaN
50%,1950.50,44.00,NaN,NaN,NaN,60.00,NaN,NaN,NaN,NaN,3.80,NaN,NaN,NaN,NaN,25.00,NaN,NaN
75%,2925.25,57.00,NaN,NaN,NaN,81.00,NaN,NaN,NaN,NaN,4.40,NaN,NaN,NaN,NaN,38.00,NaN,NaN
max,3900.00,70.00,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN,5.00,NaN,NaN,NaN,NaN,50.00,NaN,NaN

In [5]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [6]:

#df['Review Rating'].fillna(df['Review Rating'].median(), inplace=True)
df["Review Rating"] = df.groupby("Category")["Review Rating"].transform(lambda x : x.fillna(x.median()) )

In [7]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [8]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(" ","_")
df = df.rename(columns={"purchase_amount_(usd)": "purchase_amount"})

In [13]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases', 'age_group'],
      dtype='str')

In [11]:
labels =["Young Adult","Adult","Middle Age","Senior"]
df["age_group"] =  pd.qcut(df["age"],q=4,labels =labels)

In [14]:
df["age_group"].value_counts()

age_group
Young Adult    1028
Middle Age      986
Senior          944
Adult           942
Name: count, dtype: int64

In [15]:
df["age_group"].value_counts()        # should be ~975 each
df.groupby("age_group")["age"].agg(["min","max","count"])  # see actual ranges

             min  max  count
age_group
Young Adult   18   31   1028
Adult         32   44    942
Middle Age    45   57    986
Senior        58   70    944

In [16]:
df["frequency_of_purchases"].value_counts()

frequency_of_purchases
Every 3 Months    584
Annually          572
Quarterly         563
Monthly           553
Bi-Weekly         547
Fortnightly       542
Weekly            539
Name: count, dtype: int64

In [17]:
df["frequency_of_purchases"].unique()

<StringArray>
[   'Fortnightly',         'Weekly',       'Annually',      'Quarterly',
      'Bi-Weekly',        'Monthly', 'Every 3 Months']
Length: 7, dtype: str

In [18]:
#create a purchase_frequecy_days:
purchase_mapping  = {'Fortnightly' : 14,'Weekly' :7,'Annually':365,'Quarterly' :90,
      'Bi-Weekly' : 14, 'Monthly' : 30, 'Every 3 Months' : 90}

df["purchase_frequecy_days"] = df["frequency_of_purchases"].map(purchase_mapping)

In [19]:
df[["purchase_frequecy_days","frequency_of_purchases"]].head()

   purchase_frequecy_days frequency_of_purchases
0                      14            Fortnightly
1                      14            Fortnightly
2                       7                 Weekly
3                       7                 Weekly
4                     365               Annually

In [20]:
(df['promo_code_used'] == df['discount_applied']).all()

np.True_

In [21]:
df = df.drop('promo_code_used',axis=1)

In [ ]:
# Step 1: Connect to PostgreSQL
# Replace placeholders with your actual details
username = "postgres"        # default user
password = "hana0726"        # the password you set during installation
host = "localhost"           # if running locally
port = "5432"                # default PostgreSQL port
database = "Customer_behavior"  # the database you created in pgAdmin

from sqlalchemy import create_engine

engine = create_engine(
    f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}"
)

# Step 2: Load DataFrame into PostgreSQL
table_name = "customer"  # choose any table name

df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

Data successfully loaded into table 'customer' in database 'Customer_behavior'.

: